import { STATUS } from '.';

export const mockupDegens = [
  {
    img: '/img/degens/1.png',
    name: 'Perculeez',
    role: 'RHO',
    state: {
      score: 14000,
      maxDamage: 5120,
      damageCap: 16,
      status: STATUS.BOUNTY,
    },
    inventory: [
      {
        img: '/img/item/2.png',
        title: 'MONTE .44',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: true,
      },
      {
        img: '/img/item/1.png',
        title: 'Vyper P1',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: true,
      },
      {
        img: '/img/item/3.png',
        title: 'WEAPON 4',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: false,
      },
      {
        img: '/img/item/4.png',
        title: 'WEAPON 5',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: false,
      },
      {
        img: '/img/item/5.png',
        title: 'WEAPON 6',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: false,
      },
      {
        img: '/img/item/6.png',
        title: 'WEAPON 7',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: false,
      },
      {
        img: '/img/item/8.png',
        title: 'BLUBRRY MODEL A',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: true,
      },
      {
        img: '/img/item/8.png',
        title: 'WEAPON 9',
        type: 'WEAPON',
        description: 'A powerful revolver that packs a punch',
        status: 7000,
        amount: -1,
        equipped: false,
      },
    ],
  },
];
